### ISSUE TITLE
Implementing Horizontal Scrolling with Marquee Effect and Mouse Tooltip Precision

### ISSUE THREAD

**Issue by neerajbelsare** [Schwarz-Official/Schwarz#14]
We are looking to incorporate a horizontal scrolling effect with a marquee-like appearance, coupled with precise mouse tooltips aligned with the cursor's position. This enhancement will enhance user engagement and navigation.

**Comment by HariKrishna-28** [comment]
Hello! I would like to contribute. Could you please tell me more about the issue??

**Comment by jainendra001** [comment]
Hi @neerajbelsare  I am really interested to work on this issue, I am currently a fullstack developer pursuing undergrad at IIT's , Could you please assign me this issue.

**Comment by yakatyansh** [comment]
hey @neerajbelsare would love to work on this issue, can you describe more about it ?

**Comment by neerajbelsare** [comment]
Hey @HariKrishna-28 and @yakatyansh, the description for this issue will be updated very soon, probably by tomorrow. Some visual samples will be provided, along with a more detailed workflow. Meanwhile, I've assigned the issue to you.
