### ISSUE TITLE
Creating Scroll-Based Animations, Both Horizontal and Vertical, Using GSAP ScrollTrigger

### ISSUE THREAD

**Issue by neerajbelsare** [Schwarz-Official/Schwarz#15]
Our goal is to implement scroll-triggered animations that respond to both horizontal and vertical scroll actions. We intend to employ the GSAP ScrollTrigger library to seamlessly integrate these animations into our web application.

**Comment by akssshh** [comment]
hey @neerajbelsare can you assign this to me?

**Comment by subham-byte** [comment]
I would like to contribute to your project.
