### ISSUE TITLE
Designing an Optimal 3D Object Rotating Pre-loader for the Website

### ISSUE THREAD

**Issue by neerajbelsare** [Schwarz-Official/Schwarz#16]
We aim to design and implement an efficient 3D object rotating pre-loader for our website. This pre-loader will provide an appealing visual experience to users while efficiently loading website content, ensuring a positive first impression.

**Comment by theDevSoham** [comment]
Heyy @neerajbelsare was checking out for hacktoberfest challenges and landed here. Would love to take up the task.

**Comment by neerajbelsare** [comment]
Hey @theDevSoham,

Thank you for expressing your interest in taking up the task! I'm glad to hear that you're excited about contributing to the project.

I want to inform you that I am currently in the process of setting up the repository contribution guidelines and adding additional details regarding the issues. Please expect these guidelines and additional information to be available by tomorrow. Your patience is highly appreciated.

I will assign you the issue for now. Looking forward to our collaboration!

**Comment by ananyapillai72** [comment]
Hey! I am interested to do this contribution. But wanted to know, currently when I opened the website from my end I coudn't see anything on the page. Is that the case?

**Comment by neerajbelsare** [comment]
Hey @ananyapillai72,
Thank you for expressing your interest in taking up the task!

**Comment by ananyapillai72** [comment]
> Hey @ananyapillai72, Thank you for expressing your interest in taking up the task! The website currently doesn't have a landing page, which is why there is no routing for it. An issue for the same will be created shortly. Meanwhile, if you want to preview the existing pages, you can head over to the '/login', '/register' or '/auth' routes.

Hey! I am new to open source and would like to learn about it. I have cloned your repo and forked it, but unable to push it.  Its showing permission denied. Any specific reason?

**Comment by neerajbelsare** [comment]
Hey @ananyapillai72, which repository are you pushing your code to? The forked or the original repository? You need to push your code the forked repo first and then create a new pull request from the forked repo to this repo. Kindly refer to the [updated contribution guidelines for the complete details.](https://github.com/Schwarz-Official/Schwarz/blob/master/CONTRIBUTING.md#code-contributions)
