### ISSUE TITLE
Create a Contact Us page in React.js with 3D Object Animation 

### ISSUE THREAD

**Issue by ShubhamKH08** [Schwarz-Official/Schwarz#17]
**Objective**

The goal of this issue is to create a "Contact Us" page with the following features:

- Implementation in React.js.

- Integration of a 3D object that rotates smoothly on the page.

- A visually appealing design that aligns with our project's theme.

**Tasks**

-  Set up a new React.js component for the page.

-  Choose a relevant 3D object (e.g., a mailbox, envelope or any object suitable for a page).

-  Implement the 3D object animation using React Fiber or other React.js libraries.

-  Style the page to match our project's design guidelines.

-  Ensure responsiveness for various screen sizes.

**Additional Information**

- You can use any 3D library compatible with React.js, such as Three.js, to create the rotating object.

- Feel free to use CSS animations or transitions to enhance the visual effects.

- To ensure your contributions align with our design guidelines and rules, we invite you to explore our [Figma design](https://www.figma.com/file/69KAMqZl3W80QZZ7LLsHnt/Schwarz-Prototype?type=design&node-id=0%3A1&mode=design&t=460OlfVG2HfDnMsu-1). It provides valuable insights into our design principles and components.

Figma Design Reference: [Schwarz Figma Design](https://www.figma.com/file/69KAMqZl3W80QZZ7LLsHnt/Schwarz-Prototype?type=design&node-id=0%3A1&mode=design&t=460OlfVG2HfDnMsu-1)

**Comment by lokesh-wagh** [comment]
hey I would like to work on this issue

I know a little bit of three js


can you assign this issue to me

**Comment by ShubhamKH08** [comment]
Dear Schwarz Contributors,

To ensure your contributions align with our design guidelines and rules, we invite you to explore our Figma design. It provides valuable insights into our design principles and components.

Figma Design Reference: [Schwarz Figma Design](https://www.figma.com/file/69KAMqZl3W80QZZ7LLsHnt/Schwarz-Prototype?type=design&node-id=0%3A1&mode=design&t=460OlfVG2HfDnMsu-1)

Your efforts in maintaining a cohesive design are greatly appreciated.

**Comment by lokesh-wagh** [comment]
@ShubhamKH08 is there a discord group for this project
