### ISSUE TITLE
Add CI/CD workflow to check backend code formatting

### ISSUE THREAD

**Issue by MannuVilasara** [Schwarz-Official/Schwarz#28]
Please assign me this under hacktoberfest.

Will be adding CI/CD workflow to check formatting of the code.

Here's example:
- not formatted code.
![unsuccess](https://github.com/Bulkmailer/BulkMailer-Backend/assets/117009138/ad00dcb0-72bb-4a25-b191-85e1c7b537d5)
- formatted code
![success](https://github.com/Bulkmailer/BulkMailer-Backend/assets/117009138/c9c63dcb-035f-4dc6-a828-d1916e3867d5)

**Comment by MannuVilasara** [comment]
Can you please assign me this issue

**Comment by neerajbelsare** [comment]
Hey @MannuVilasara, I've assigned the issue to you.

**Comment by MannuVilasara** [comment]
Please Review the PR #29

**Comment by neerajbelsare** [comment]
Hey @MannuVilasara,
Your pull request has been merged! Thanks a ton for your awesome contribution. Your help means a lot! Could you please take a moment to star the repository? It helps us a bunch! ⭐️
